'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'

const vehicles = [
  { id: 1, make: 'Toyota', model: 'Harrier', year: 2020, price: 4850000, mileage: 48000, transmission: 'Automatic', fuel: 'Petrol', body: 'SUV', location: 'Mombasa', image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85', featured: true },
  { id: 2, make: 'Mazda', model: 'CX-5', year: 2021, price: 4250000, mileage: 36000, transmission: 'Automatic', fuel: 'Petrol', body: 'SUV', location: 'Nairobi', image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85', featured: true },
  { id: 3, make: 'Subaru', model: 'Forester', year: 2019, price: 3180000, mileage: 62000, transmission: 'Automatic', fuel: 'Petrol', body: 'SUV', location: 'Mombasa', image: 'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=85', featured: false },
  { id: 4, make: 'Mercedes-Benz', model: 'C-Class', year: 2022, price: 7950000, mileage: 18000, transmission: 'Automatic', fuel: 'Petrol', body: 'Sedan', location: 'Nairobi', image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=85', featured: true },
  { id: 5, make: 'BMW', model: 'X3', year: 2020, price: 6850000, mileage: 41000, transmission: 'Automatic', fuel: 'Diesel', body: 'SUV', location: 'Mombasa', image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85', featured: false },
  { id: 6, make: 'Nissan', model: 'X-Trail', year: 2018, price: 2480000, mileage: 78000, transmission: 'Automatic', fuel: 'Petrol', body: 'SUV', location: 'Kisumu', image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=85', featured: false },
]

const formatPrice = (price: number) => `KSh ${(price / 1000000).toFixed(2)}M`

function VehicleCard({ vehicle, saved, onSave }: { vehicle: typeof vehicles[number], saved: boolean, onSave: (id: number) => void }) {
  return <article className="vehicle-card">
    <div className="vehicle-image-wrap"><img src={vehicle.image} alt={`${vehicle.year} ${vehicle.make} ${vehicle.model}`} /><span className="status-pill">Available</span><button className={`save-button ${saved ? 'saved' : ''}`} onClick={() => onSave(vehicle.id)} aria-label="Shortlist vehicle">{saved ? '♥' : '♡'}</button></div>
    <div className="vehicle-card-body"><div className="eyebrow">{vehicle.make} · {vehicle.year}</div><h3>{vehicle.model}</h3><div className="vehicle-price">{formatPrice(vehicle.price)}</div><div className="vehicle-meta"><span>{vehicle.mileage.toLocaleString()} km</span><span>{vehicle.transmission}</span><span>{vehicle.fuel}</span></div><div className="vehicle-location">⌖ {vehicle.location}</div><div className="card-actions"><Link href={`/cars/${vehicle.make.toLowerCase()}/${vehicle.model.toLowerCase()}`} className="text-link">View details <span>↗</span></Link><button className="inquire-button" onClick={() => window.location.href = `mailto:hello@clearlakeautomotives.co.ke?subject=Inquiry about ${vehicle.year} ${vehicle.make} ${vehicle.model}`}>Inquire</button></div></div>
  </article>
}

export default function Home() {
  const [query, setQuery] = useState('')
  const [saved, setSaved] = useState<number[]>([])
  const [menu, setMenu] = useState(false)
  useEffect(() => { const stored = window.localStorage.getItem('clearlake-shortlist'); if (stored) setSaved(JSON.parse(stored)) }, [])
  const toggleSave = (id: number) => { const next = saved.includes(id) ? saved.filter(x => x !== id) : [...saved, id]; setSaved(next); window.localStorage.setItem('clearlake-shortlist', JSON.stringify(next)) }
  const suggestions = useMemo(() => query.length < 2 ? [] : vehicles.filter(v => `${v.make} ${v.model}`.toLowerCase().includes(query.toLowerCase())).slice(0, 5), [query])
  return <main>
    <header className="site-header"><Link href="/" className="brand"><span className="brand-mark">C</span><span><strong>Clearlake</strong><small>Automotives · Mombasa</small></span></Link><nav className={menu ? 'open' : ''}><Link href="/">Home</Link><Link href="#inventory">Browse Cars</Link><Link href="/shortlist">Shortlist {saved.length > 0 && <b>{saved.length}</b>}</Link><Link href="#about">About</Link><Link href="#contact">Contact</Link></nav><div className="header-actions"><button className="search-icon" aria-label="Search">⌕</button><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? '×' : '☰'}</button></div></header>
    <section className="hero"><div className="hero-copy"><div className="kicker"><span className="kicker-line" /> MOMBASA · KENYA</div><h1>Find the right car.<br /><em>We'll do the heavy lifting.</em></h1><p>Tell us what you're looking for and we'll help you find the right vehicle, connect you with the dealership, and help arrange delivery when needed.</p><div className="hero-actions"><Link href="#find" className="button button-dark">Find My Car <span>↗</span></Link><Link href="#inventory" className="button button-light">Browse cars</Link></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1600&q=90" alt="Premium dark SUV on a coastal road" /><div className="hero-caption"><span>Curated vehicles</span><strong>For the way ahead.</strong></div></div></section>
    <section className="search-section"><div className="section-label">START YOUR SEARCH</div><div className="search-box"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by brand, model or keyword..." /><Link href={query ? `/cars?search=${encodeURIComponent(query)}` : '#inventory'}>Search</Link>{suggestions.length > 0 && <div className="suggestions">{suggestions.map(v => <Link key={v.id} href={`/cars/${v.make.toLowerCase()}/${v.model.toLowerCase()}`}><span>{v.make}</span> {v.model}<small>{v.year} · {formatPrice(v.price)}</small></Link>)}</div>}</div><div className="search-note">We connect you with the right people. You verify, decide and transact directly with the seller.</div></section>
    <section className="trust-strip"><div className="trust-icon">✦</div><div><strong>A clearer way to buy a car</strong><p>Clearlake Automotives helps you search for suitable vehicles, connect with dealerships and arrange the next steps. We do not ask customers to send us money simply for finding or connecting them with a vehicle. Always verify vehicle details, ownership, pricing and payment arrangements directly with the relevant dealership or seller.</p></div><Link href="#about">How it works <span>↗</span></Link></section>
    <section className="inventory-section" id="inventory"><div className="section-heading"><div><div className="section-label">THE COLLECTION</div><h2>Vehicles worth<br /><em>looking closer at.</em></h2></div><Link href="/cars" className="text-link">View all cars <span>↗</span></Link></div><div className="vehicle-grid">{vehicles.slice(0, 3).map(v => <VehicleCard key={v.id} vehicle={v} saved={saved.includes(v.id)} onSave={toggleSave} />)}</div></section>
    <section className="find-section" id="find"><div><div className="section-label light">PERSONAL SEARCH SERVICE</div><h2>Looking for something<br /><em>specific?</em></h2><p>Give us the brief. We'll search our network, compare the options and bring you the ones worth your time.</p><Link href="/find-my-car" className="button button-light">Tell us what you need <span>↗</span></Link></div><div className="find-stat"><strong>01</strong><span>Tell us your<br />ideal car</span><strong>02</strong><span>We search our<br />network</span><strong>03</strong><span>You make<br />the call</span></div></section>
    <section className="about-section" id="about"><div className="section-label">THE CLEarlake DIFFERENCE</div><h2>A better way to<br /><em>find your next car.</em></h2><div className="about-grid"><p>Car buying can be noisy. We make it straightforward. Clearlake Automotives is a vehicle-finding and brokerage service built around your needs — not a lot of stock on a forecourt.</p><div className="about-points"><div><span>01</span><strong>Curated options</strong><p>We narrow the market to vehicles that fit your brief.</p></div><div><span>02</span><strong>Clear connections</strong><p>We help you reach the dealership or seller when it matters.</p></div><div><span>03</span><strong>Beyond Mombasa</strong><p>Ask us about viewing and transportation options wherever you are.</p></div></div></div></section>
    <footer id="contact"><div className="footer-brand"><Link href="/" className="brand"><span className="brand-mark">C</span><span><strong>Clearlake</strong><small>Automotives · Mombasa</small></span></Link><p>Find better. Drive clearer.</p></div><div className="footer-links"><div><span>Explore</span><Link href="#inventory">Browse cars</Link><Link href="/find-my-car">Find my car</Link><Link href="/shortlist">My shortlist</Link></div><div><span>Get in touch</span><a href="tel:+254700000000">+254 700 000 000</a><a href="mailto:hello@clearlakeautomotives.co.ke">hello@clearlakeautomotives.co.ke</a><p>Mombasa, Kenya</p></div></div><div className="footer-bottom">© 2026 Clearlake Automotives <span>Vehicle-finding service · Verify before you transact</span></div></footer>
  </main>
}

